config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  
  resources :users
  resources :parameter_categories, :except => 'show'
  resources :parameters, :except => 'show'
  resources :criteria, :except => 'show'
  
  resources :articles do
    collection do
      get 'list'
    end
  end

  resources :documentations do
    collection do
      get 'list'
    end
  end 

  resources :locations, :except => 'show' do
    collection do
      get 'get_by_river'
    end
  end
  resources :analytics, :except => 'show' do
    collection do
      get 'filter'
    end
  end

  resources :discussions do 
    collection do
      get 'get_more_data'
    end
  end

  get '/home', to: 'home#index'
  get '/results/analytics', to: 'results#analytics'
  get '/results/analytics/chart', to: 'results#analytic_charts'
  get '/results/location', to: 'results#location'
  get '/results/get_all_location', to: 'results#get_all_location'
  get '/results/get_analytics', to: 'results#get_analytics'
  get '/results/get_analytic_charts', to: 'results#get_analytic_charts'
  get '/results/save_analytic_as_pdf', to: 'results#save_analytic_as_pdf'
  get '/results/save_analytic_chart_as_pdf', to: 'results#save_analytic_chart_as_pdf'
  get '/results/save_map_image_as_pdf', to: 'results#save_map_image_as_pdf'
  get '/download_history', to: 'download_histories#index'
  root to: 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]
  before_action :find_discussion, only: [:edit, :update]

  def index
    session[:offset] = 0
    get_data(session[:offset])
  end

  def create
    begin
      @comment = Comment.new(name: params[:name], email: params[:email], message: params[:message])
      @comment.parent_id = params[:parent_id] if params[:parent_id].present?
      if @comment.save!
        @response = {success: true}
        job_params = {type: "discuss", comment: @comment}
        SendEmailJob.set(wait: 10.seconds).perform_later(job_params)
      else
        @response = {success: false, error: "Terjadi kesalahan pada saat penyimpanan data, silakan coba lagi"}
      end
        
    rescue Exception => e
      @response = {success: false, comment: @comment}
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    begin
      @comment.message = params[:message]
      if @comment.save!
        @response = {success: true}
      else
        @response = {success: false, error: "Terjadi kesalahan pada saat penyimpanan data, silakan coba lagi"}
      end
    rescue Exception => e
      @response = {success: false, comment: @comment}
    end

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comment = Comment.destroy(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def get_more_data
    session[:offset] = session[:offset] + 1
    get_data(session[:offset])
    respond_to do |format|
      format.js
    end
  end

  private
  def get_data(offset)
    limit = 5
    @comments = Comment.isParent().order('created_at DESC').limit(limit).offset(offset * limit)
  end

  def find_discussion
    @comment = Comment.find(params[:id])
  end
end

app/views/discussions/_child_comment.html.erb
<li class="child-comment <%= is_new ? 'new-comment' : '' %>" id="comment_<%= child.id %>">
  <div class="well">
    <div class="row">
      <div class="col-md-9 col-xs-12">
        <h4 class="pull-left"><%= child.name%> :</h4>
      </div>
      <div class="col-md-3 col-xs-12">
        <h4><small style="float:right;"><i class="fa fa-pencil-square-o"></i> <%= child.created_at.strftime('%d-%m-%Y %H:%M')%></small></h4>
      </div>
    </div>
    <div class="row comment-container">
      <div class="col-md-12 col-xs-12">
        <p style="padding-left:5px;">
          <em id="messages_<%= child.id %>"><%= child.message%></em>
        </p>
      </div>
      <div class="col-md-12 col-xs-12">
        <p class="pull-left">
          <!-- TODO: Change edit and remove fuction -->
          <% if can? :update, Comment %>
            <% if current_user.email == child.email %>
              <%= link_to"<i class='fa fa-pencil'></i> Edit".html_safe, edit_discussion_path(child.id), :class => "btn btn-success btn-xs", :remote => true %>
            <% end %>
          <% end %>

          <% if can? :destroy, Comment %>
            <%= link_to "<i class='fa fa-trash'></i> Hapus".html_safe, discussion_url(child), :data => {:confirm => 'Apakah anda yakin?'}, :method => :delete, :class => "btn btn-success btn-xs", :remote => true %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</li>

app/views/discussions/_comment.html.erb
<li class="comment" id="comment_<%= comment.id %>" >
  <div class="well <%= is_new ? 'new-comment' : '' %>">
    <div class="row">
      <div class="col-md-10 col-xs-12">
        <h4 class="pull-left"><%= comment.name%> :</h4>
      </div>
      <div class="col-md-2 col-xs-12">
        <h4><small><i class="fa fa-pencil-square-o"></i> <%= comment.created_at.strftime('%d-%m-%Y %H:%M')%></small></h4>
      </div>
    </div>
    <div class="row comment-container">
      <div class="col-md-12 col-xs-12">
        <p style="padding-left:5px;">
          <em id="messages_<%= comment.id %>"><%= comment.message%></em>
        </p>
      </div>
      <div class="col-md-12 col-xs-12">
        <p class="pull-left">
          <a class="reply-link btn btn-success btn-xs" href="#discussionForm" data-sender="<%= comment.name%>" data-comment-id="<%= comment.id%>" data-turbolinks="false"><i class="fa fa-reply"></i>Balas</a>
          
          <% if can? :update, Comment %>
            <% if current_user.email == comment.email %>
              <%= link_to"<i class='fa fa-pencil'></i> Edit".html_safe, edit_discussion_path(comment.id), :class => "btn btn-success btn-xs", :remote => true %>
            <% end %>
          <% end %>
          
          <% if can? :destroy, Comment %>
            <%= link_to "<i class='fa fa-trash'></i> Hapus".html_safe, discussion_url(comment), :data => {:confirm => 'Apakah anda yakin?'}, :method => :delete, :class => "btn btn-success btn-xs", :remote => true %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-xs-12">
      <a type="button" data-toggle="collapse" data-target="#<%= "child_comments_#{comment.id}" %>" aria-expanded="true" aria-controls="<%= "child_comments_#{comment.id}" %>" id="<%= "replies_button_#{comment.id}" %>" class="<%= "hide" unless comment.childs.any?  %>">Balasan</a>
    </div>
  </div>
  <ul class="collapse" id="<%= "child_comments_#{comment.id}" %>">
    <% if comment.childs.any? %>
      <% comment.childs.each do |child| %>
        <%= render :partial => 'child_comment', :locals => {:comment => comment, :child => child, :is_new => false} %>
      <% end %>
    <% end %>
  </ul>
</li>

app/views/discussions/_form.erb
<h4><%= is_create ? "Tinggalkan Pesan" : "Ubah Pesan"%></h4>
<%= form_tag(is_create ? discussions_path(format: :js) : discussion_path(comment.id), method: is_create ? 'post' : 'put', remote: true, class: 'clearfix') do %>
  <%= hidden_field_tag :id, !is_create ? comment.id : nil %>
  <div class="col-md-6 form-group">
    <%= label_tag :name, "Nama", class: "sr-only" %>
    <%= text_field_tag :name, current_user.present? ? current_user.name : nil, class: "form-control", placeholder: "Nama", :readonly => current_user.present? ? true : false %>
  </div>
  <div class="col-md-6 form-group">
    <%= label_tag :email, "Email", class: "sr-only" %>
    <%= text_field_tag :email, current_user.present? ? current_user.email : nil, class: "form-control", placeholder: "Email", :readonly => current_user.present? ? true : false %>
  </div>
  <div class="col-md-12 form-group">
    <%= label_tag :message, "Pesan", class: "sr-only" %>
    <%= text_area_tag :message, !is_create ? comment.message : nil, class: "form-control", placeholder: "Pesan" %>
  </div>
  <div class="col-md-12 form-group text-right">
    <%= hidden_field_tag :parent_id, !is_create ? comment.parent_id : nil %>
    <%= button_tag(type: "submit", class: "btn btn-success") do %>
      <i class="fa fa-floppy-o"></i> Simpan
    <% end %>
  </div>
<% end %>

app/views/discussions/create.js.erb
$('html,body').animate({
  scrollTop: 0
}, 700);
<% if (@response[:success]) %>
  <% if (@comment.parent_id.present?) %>
    var item = $("<%= escape_javascript render(:partial => 'child_comment', :locals => { :comment => @comment.parent, :child => @comment, :is_new => 'true' }) %>").hide().fadeIn(1000);
    if ($('#child_comments_<%= @comment.parent_id%> li').length == 0) {
      $("#replies_button_<%=@comment.parent_id %>").removeClass('hide');
    };
    $('#child_comments_<%= @comment.parent_id%>').prepend(item);
    $("#parent_id").val("");
    $("#alert-reply").addClass("hide");
  <% else %>
    var item = $("<%= escape_javascript render(:partial => 'comment', :locals => { :comment => @comment, :is_new => 'true' }) %>").hide().fadeIn(1000);
    $('#comments').prepend(item);
  <% end %>
  
  <% unless current_user.present? %>
    $("#discussionForm form").find("input[type=text]").val("");
  <% end %>
  $("#discussionForm form").find("textarea").val("");
  $("#page-content").prepend('<div id="success-alert-discussion" class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>Komentar telah berhasil disimpan</div>');
<% else %>
  var errors = $("<%= escape_javascript render(:partial => 'shared/error_messages', :locals => { :obj => @comment}) %>");
  $("#page-content").prepend(errors);
<% end %>

app/views/discussions/destroy.js.erb
var parentId = $('#comment_<%= @comment.id %>').closest('ul').attr('id');
$('#comment_<%= @comment.id %>').remove();
if (parentId == "child_comments_<%= @comment.parent_id %>") {
	if ($('#'+ parentId + ' li').length == 0) {
		$("#replies_button_<%=@comment.parent_id %>").addClass('hide');
	};
};

app/views/discussions/edit.js.erb
window.scrollTo(0,document.body.scrollHeight);
$('#commentForm').html("<%= escape_javascript render(:partial => 'form', :locals => { :is_create => false, :comment => @comment }) %>");

app/views/discussions/get_more_data.js.erb
<% if (@comments.any?)%>
  <% @comments.each do |comment| %>
    var item = $("<%= escape_javascript render(:partial => 'comment', :locals => { :comment => comment, :is_new => false }) %>").hide().fadeIn(1000);
    $('#comments').append(item);
  <% end %>
<% end %>

app/views/discussions/index.html.erb
<div class="header-content">
  <h2 class="page-header">Diskusi</h2>
</div>
<% if @comments.any? %>
  <div class="row">
    <div class="col-md-12">
      <ul id="comments" class="comments">
        <% @comments.each do |comment| %>
          <%= render :partial => 'comment', :locals => {:comment => comment, :is_new => false} %>
        <% end %>
      </ul>
    </div>
    <div class="col-md-12 center">
      <%= link_to "<i class='fa fa-cog'></i> Lihat data lainnya".html_safe, get_more_data_discussions_path, class: "btn btn-success", remote: true %>
    </div>
  </div>
<%else%>
  <%= render :partial => 'shared/no-data'%>
<%end%>
<br/>
<div id="discussionForm" class="well">
  <div id="alert-reply" class="alert alert-success alert-dismissible fade in hide" role="alert">
    <p class="content"></p>
    <p><button id="backBtn" type="button" class="btn btn-default"><i class="fa fa-times"></i>Batal</button></p>
  </div>
  <div id="commentForm">
    <%= render :partial => 'form', :locals => {:is_create => true} %>    
  </div>  
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $("ul#comments").on("click", "a.reply-link", function(){
      var parent_id = $(this).data("comment-id");
      var sender = $(this).data("sender");
      $("#parent_id").val(parent_id);
      $("#alert-reply p.content").html("Anda sedang membalas komentar dari <strong>" + sender + "</strong>");
      $("#alert-reply").removeClass("hide");
    });

    $("#backBtn").on("click", function(){
      $("#parent_id").val("");
      $("#alert-reply").addClass("hide");
    })

    $( document ).on("mouseover", ".new-comment", function(ev, el){
      $(this).removeClass('new-comment');
    });
  });
</script>

app/views/discussions/update.js.erb
$('html,body').animate({
  scrollTop: 0
}, 700);
<% if (@response[:success]) %>
  $("#comment_<%= @comment.id %> #messages_<%= @comment.id %>").html("<%= @comment.message %>");
  $("#page-content").prepend('<div id="success-alert-discussion" class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>Komentar telah berhasil disimpan</div>');
<% else %>
  var errors = $("<%= escape_javascript render(:partial => 'shared/error_messages', :locals => { :obj => @comment}) %>");
  $("#page-content").prepend(errors);
<% end %>
$('#commentForm').html("<%= escape_javascript render(:partial => 'form', :locals => { :is_create => true }) %>");