config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  
  resources :users
  resources :parameter_categories, :except => 'show'
  resources :parameters, :except => 'show'
  resources :criteria, :except => 'show'
  
  resources :articles do
    collection do
      get 'list'
    end
  end

  resources :documentations do
    collection do
      get 'list'
    end
  end 

  resources :locations, :except => 'show' do
    collection do
      get 'get_by_river'
    end
  end
  resources :analytics, :except => 'show' do
    collection do
      get 'filter'
    end
  end

  resources :discussions do 
    collection do
      get 'get_more_data'
    end
  end

  get '/home', to: 'home#index'
  get '/results/analytics', to: 'results#analytics'
  get '/results/analytics/chart', to: 'results#analytic_charts'
  get '/results/location', to: 'results#location'
  get '/results/get_all_location', to: 'results#get_all_location'
  get '/results/get_analytics', to: 'results#get_analytics'
  get '/results/get_analytic_charts', to: 'results#get_analytic_charts'
  get '/results/save_analytic_as_pdf', to: 'results#save_analytic_as_pdf'
  get '/results/save_analytic_chart_as_pdf', to: 'results#save_analytic_chart_as_pdf'
  get '/results/save_map_image_as_pdf', to: 'results#save_map_image_as_pdf'
  get '/download_history', to: 'download_histories#index'
  root to: 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/parameter_category.rb
class ParameterCategory < ApplicationRecord
  # validates :name, presence: true
  validate :must_be_presents
  
  has_many :parameters

  def must_be_presents
    errors[:base] << "Nama tidak boleh kosong" if name.blank?
  end
end

app/controllers/parameter_categories_controller.rb
class ParameterCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_parameter_category, only: [:edit, :update, :destroy]
  
  def index
    @parameter_categories = ParameterCategory.order('created_at DESC')
  end

  def new
    @parameter_category = ParameterCategory.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    begin
      @parameter_category = ParameterCategory.new(parameter_category_params)
      if @parameter_category.save!
        redirect_to parameter_categories_path
      else
        render 'new'
      end  
    rescue Exception => e
      render 'new'
    end
     
  end

  def edit
  end

  def update
    begin
      if @parameter_category.update_attributes(parameter_category_params)
        redirect_to parameter_categories_path
      else
        render 'edit'
      end  
    rescue Exception => e
      render 'edit'
    end
    
  end

  def destroy
    @parameter_category.destroy!
    redirect_to parameter_categories_path
  end

  private

  def parameter_category_params
    params.require(:parameter_category).permit(:name)
  end

  def find_parameter_category
    @parameter_category = ParameterCategory.find(params[:id])
  end
end

app/views/parameter_categories/_form.html.erb
<%= form_for(@parameter_category, html:{class: 'form-horizontal'}) do |f| %>
  <div class="form-group required">
    <%= f.label :name, "Nama Kategori", class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-8">
      <%= link_to "<i class='fa fa-reply'></i> Batal".html_safe, { controller: "parameter_categories", action: "index" }, class: "btn btn-default" %>
      <%#= f.submit "Simpan", class: "btn btn-success" %>
      <%= button_tag(type: "submit", class: "btn btn-success") do %>
        <i class="fa fa-floppy-o"></i> Simpan
      <% end %>
    </div>
  </div>
<% end %>

app/views/parameter_categories/edit.html.erb
<%= render :partial => 'shared/error_messages', :locals => {:obj => @parameter_category} %>

<h2 class="page-header">Edit Kategori Parameter</h2>
<%= render :partial => 'form' %>

app/views/parameter_categories/index.html.erb
<div class="header-content">
  <h2 class="page-header">Daftar Kategori Parameter</h2>
</div>
<table id="article-table" class="display table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nama</th>
      <th>Tanggal dibuat</th>
    </tr>
  </thead>
  <% @parameter_categories.each do |p| %>
    <tr>
      <td>
        <%= "#{p.name}" %>
        <div class="btn-group" style="float: right;">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to_if(can?(:edit, ParameterCategory), "<i class='fa fa-pencil-square-o'></i> Ubah".html_safe, edit_parameter_category_path(p.id)) {} %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to_if(can?(:delete, p), "<i class='fa fa-times'></i> Hapus".html_safe, p, :data => {:confirm => 'Apakah anda yakin?'}, :method => :delete) {} %></li>
          </ul>
        </div>
      </td>
      <td><%= "#{p.created_at.strftime('%d-%m-%Y')}" %></td>
    </tr>
  <% end %>
</table>
<script type="text/javascript">
  $(document).ready(function() {
    $('#article-table').DataTable({
      oLanguage: { sEmptyTable: "Data tidak ditemukan" },
      dom: "<'row'<'col-sm-6'B><'col-sm-6'f>><'row'<'col-sm-12't>><'row'<'col-sm-12'p>>",
      buttons: [
        {
          text: '<i class="fa fa-plus"></i> Tambah',
          className: 'btn btn-success',
          action: function(e, dt, node, config) {
            window.location.href = '/parameter_categories/new';
          }
        }
      ]
    });
  });
</script>

app/views/parameter_categories/new.html.erb
<%= render :partial => 'shared/error_messages', :locals => {:obj => @parameter_category} %>

<h2 class="page-header">Tambah Kategori Paramater</h2>
<%= render :partial => 'form' %>