config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  
  resources :users
  resources :parameter_categories, :except => 'show'
  resources :parameters, :except => 'show'
  resources :criteria, :except => 'show'
  
  resources :articles do
    collection do
      get 'list'
    end
  end

  resources :documentations do
    collection do
      get 'list'
    end
  end 

  resources :locations, :except => 'show' do
    collection do
      get 'get_by_river'
    end
  end
  resources :analytics, :except => 'show' do
    collection do
      get 'filter'
    end
  end

  resources :discussions do 
    collection do
      get 'get_more_data'
    end
  end

  get '/home', to: 'home#index'
  get '/results/analytics', to: 'results#analytics'
  get '/results/analytics/chart', to: 'results#analytic_charts'
  get '/results/location', to: 'results#location'
  get '/results/get_all_location', to: 'results#get_all_location'
  get '/results/get_analytics', to: 'results#get_analytics'
  get '/results/get_analytic_charts', to: 'results#get_analytic_charts'
  get '/results/save_analytic_as_pdf', to: 'results#save_analytic_as_pdf'
  get '/results/save_analytic_chart_as_pdf', to: 'results#save_analytic_chart_as_pdf'
  get '/results/save_map_image_as_pdf', to: 'results#save_map_image_as_pdf'
  get '/download_history', to: 'download_histories#index'
  root to: 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/article.rb
class Article < ApplicationRecord
	# validates :title, presence: true
	# validates :content, presence: true
	validate :must_be_presents
	
	belongs_to :documentation
	belongs_to :user

	self.per_page = 10

	def must_be_presents
    errors[:base] << "Judul tidak boleh kosong" if title.blank?
    errors[:base] << "Konten tidak boleh kosong" if content.blank?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_article, only: [:edit, :update, :destroy, :show]
  
  def index
    @articles = Article.paginate(:page => params[:page]).order('created_at DESC')    
  end

  def show
  end

  # page for administrator
  # ==========================================================
  def list
    @articles = Article.order('created_at DESC')
  end

  def new
    @article = Article.new
  end

  def create
    begin
      @article = Article.new(article_params)
    
      if params[:article][:image].present?
        documentation = Documentation.find_or_create_by(title: params[:article][:title]) do |d|
          d.image = params[:article][:image]
          d.is_article = true
        end
        if documentation.errors.any?
          @article.errors.add(:documentation, "Anda tidak dapat meng-upload foto lebih dari 1MB")
          raise @article.errors.messages
        end
        @article.documentation = documentation
      end

      @article.content_preview = create_article_preview(params[:article][:content])
      @article.user = current_user

      if @article.save!
        redirect_to list_articles_path
      else
        if documentation.present?
          documentation.destroy!
        end
        render 'new'
      end  
    rescue Exception => e
      render 'new'
    end
     
  end

  def edit
  end

  def update
    begin
      if params[:article][:image].present?
        if @article.documentation_id?
          documentation = Documentation.find(@article.documentation_id)
          documentation.image = params[:article][:image]
          documentation.is_article = true
          documentation.save!
        else
          documentation = Documentation.find_or_create_by(title: params[:article][:title]) do |d|
            d.image = params[:article][:image]
            d.is_article = true
          end
          raise "error" if documentation.errors.any?
        end
        
        params[:article][:documentation_id] = documentation.id
      end
      params[:article][:content_preview] = create_article_preview(params[:article][:content])
      params[:article][:user_id] = current_user.id
      if @article.update_attributes(article_params)
        redirect_to list_articles_path
      else
        if documentation.present?
          documentation.destroy!
        end
        render 'edit'
      end  
    rescue Exception => e
      doc_error_key = documentation.errors.messages.keys.first
      @article.errors.add(doc_error_key, documentation.errors.messages[doc_error_key].join(','))
      render 'edit'
    end
    
  end

  def destroy
    @article.destroy!
    redirect_to list_articles_path
  end
  # ==========================================================

  private

  def article_params
    params.require(:article).permit(:title, :content, :documentation_id, :user_id, :content_preview)
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def create_article_preview(content)
    temp_content = ActionController::Base.helpers.strip_tags(content)
    return ActionController::Base.helpers.truncate(temp_content, :length => 200)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html:{class: 'form-horizontal'}) do |f| %>
  <div class="form-group required">
    <%= f.label :title, "Judul", class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group required">
    <%= f.label :content, "Konten", class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :content, class: "wysiwyg-editor form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, "Foto", class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-8">
      <%= link_to "<i class='fa fa-reply'></i> Batal".html_safe, { controller: "articles", action: "list" }, class: "btn btn-default" %>
      <%= button_tag(type: "submit", class: "btn btn-success") do %>
        <i class="fa fa-floppy-o"></i> Simpan
      <% end %>
    </div>
  </div>
 
<% end %>

<script type="text/javascript">
  $(document).ready(function(){

    $('.wysiwyg-editor').each(function(i, elem) {
      $(elem).wysihtml5({
        useLineBreaks: false,
        toolbar:{
          "image": false,
          "font-styles": false,
          "emphasis": true,
          "lists": true,
          "html": false,
          "link": false  
        } 
      });
    });

  })
</script>

app/views/articles/edit.html.erb
<%= render :partial => 'shared/error_messages', :locals => {:obj => @article} %>

<h2 class="page-header">Edit Artikel</h2>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<div class="header-content">
  <h2 class="page-header">Artikel</h2>
</div>
<% if @articles.any? %>
  <% @articles.each do |article|%>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <% if article.documentation_id? %>
            <%= image_tag(article.documentation.image_url(:thumb), :class => "media-object") %>
          <% else %>
            <%= image_tag("no_image.png", :class => "media-object")%>
          <% end %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= article.title.titleize%>
        </h4>
        <small><%= "#{article.created_at.strftime('%d-%m-%Y %H:%M')}" %></small>
        <br />
        <%=article.content_preview%>
        <%= link_to "Selengkapnya", article_path(article.id) %>
      </div>
    </div>
  <% end %>
  <%= will_paginate @articles, :page_links => false, renderer: BootstrapPagination::Rails %>  
<% else %>
  <%= render :partial => 'shared/no-data'%>
  <!-- <table id="empty-result" class="table table-striped table-bordered">
    <tr>
      <td>Data tidak ditemukan</td>
    </tr>
  </table> -->
<% end %>

app/views/articles/list.html.erb
<div class="header-content">
  <h2 class="page-header">Daftar Artikel</h2>
</div>
<table id="article-table" class="display table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Judul</th>
      <th>Tanggal ditulis</th>
    </tr>
  </thead>
  <% @articles.each do |a| %>
    <tr>
      <td>
        <%= "#{a.title}" %>
        <div class="btn-group" style="float: right;">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to_if(can?(:edit, Article), "<i class='fa fa-pencil-square-o'></i> Ubah".html_safe, edit_article_path(a.id)) {} %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to_if(can?(:delete, a), "<i class='fa fa-times'></i> Hapus".html_safe, a, :data => {:confirm => 'Apakah anda yakin?'}, :method => :delete) {} %></li>
          </ul>
        </div>
      </td>
      <td><%= "#{a.created_at.strftime('%d-%m-%Y')}" %></td>
    </tr>
  <% end %>
</table>
<script type="text/javascript">
  $(document).ready(function() {
    $('#article-table').DataTable({
      oLanguage: { sEmptyTable: "Data tidak ditemukan" },
      dom: "<'row'<'col-sm-6'B><'col-sm-6'f>><'row'<'col-sm-12't>><'row'<'col-sm-12'p>>",
      buttons: [
        {
          text: '<i class="fa fa-plus"></i> Tambah',
          className: 'btn btn-success',
          action: function(e, dt, node, config) {
            window.location.href = '/articles/new';
          }
        }
      ]
    });
  });
</script>

app/views/articles/new.html.erb
<%= render :partial => 'shared/error_messages', :locals => {:obj => @article} %>

<h2 class="page-header">Tambah Artikel</h2>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div class="article">
  <div class="header-content">
    <h3 class="page-header" style="letter-spacing: -1px;font-weight: bold;"><%= @article.title.titleize%></h3>
  </div>
  <div class="author-content">
    <span>Ditulis oleh: <%= @article.user.name%></span>
    <span>Tanggal: <%= "#{@article.created_at.strftime('%d-%m-%Y %H:%M')}"%></span>
  </div>
  <div class="article-content">
    <%= image_tag(@article.documentation.image_url) if @article.documentation_id? %>
    <%= @article.content.html_safe%>
    <br/>
    <br/>
    <%= link_to "<i class='fa fa-reply'></i> Kembali".html_safe, articles_path, class: "btn btn-success" %>
  </div>
</div>