config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  
  resources :users
  resources :parameter_categories, :except => 'show'
  resources :parameters, :except => 'show'
  resources :criteria, :except => 'show'
  
  resources :articles do
    collection do
      get 'list'
    end
  end

  resources :documentations do
    collection do
      get 'list'
    end
  end 

  resources :locations, :except => 'show' do
    collection do
      get 'get_by_river'
    end
  end
  resources :analytics, :except => 'show' do
    collection do
      get 'filter'
    end
  end

  resources :discussions do 
    collection do
      get 'get_more_data'
    end
  end

  get '/home', to: 'home#index'
  get '/results/analytics', to: 'results#analytics'
  get '/results/analytics/chart', to: 'results#analytic_charts'
  get '/results/location', to: 'results#location'
  get '/results/get_all_location', to: 'results#get_all_location'
  get '/results/get_analytics', to: 'results#get_analytics'
  get '/results/get_analytic_charts', to: 'results#get_analytic_charts'
  get '/results/save_analytic_as_pdf', to: 'results#save_analytic_as_pdf'
  get '/results/save_analytic_chart_as_pdf', to: 'results#save_analytic_chart_as_pdf'
  get '/results/save_map_image_as_pdf', to: 'results#save_map_image_as_pdf'
  get '/download_history', to: 'download_histories#index'
  root to: 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  
  def analytics
    @rivers = Location::RIVERS
    @criteria = Criterium.all
  end

  def get_analytics
    session[:params] = params
    @criteria = Criterium.all
    @selected_criterium = Criterium.find(params[:criterium])
    @parameter_categories = ParameterCategory.all
    @analytics = Analytic.by_river_name_and_period(params[:river_name], params[:period_date])

    respond_to do |format|
      format.js
    end
  end

  def analytic_charts
    @rivers = Location::RIVERS
    @parameters = Parameter.for_select
    @criteria = Criterium.all
  end

  def get_analytic_charts
    start_date = DateTime.new(params["start"].to_f, 1, 1)
    end_date = DateTime.new(params["end"].to_f, 12, 31) 
    parameter = Parameter.find(params["parameter"])
    label_chart = "Grafik #{parameter.name} #{params['river']} Tahun #{start_date.strftime("%Y")}"
    label_chart = label_chart + "-#{end_date.strftime("%Y")}" if params["end"] != params["start"]
    locations = Location.by_river_name(params["river"]).sort_by{|l| l.id}.map { |l| l.code }
    data = AnalyticParameter.chart_data(params["river"], start_date, end_date, params["parameter"])
    criterium_data = CriteriumParameter.chart_data(params["parameter"], params["criterium"], locations.length)
    data << criterium_data
    session[:chart] = params
    respond_to do |format|
      format.json { render :json => {:title => label_chart, :xLabels => locations, :data => data, :unit =>  parameter.unit} }
    end
  end

  def location
    @rivers = Location::RIVERS
  end

  def get_all_location
    session[:location_params] = params
    @locations = Location.by_river_name(params[:river_name])
    respond_to do |format|
      format.js
    end
  end

  def save_map_image_as_pdf
    @locations = Location.by_river_name(session[:location_params]["river_name"])
    filename = "peta analisa #{session[:params]['river_name']}"
    if @locations.any?
      save_download_information(params, "map_location")
    end
    
    render_as_pdf('results/maps.pdf.erb', filename)
  end

  def save_analytic_as_pdf
    @criteria = Criterium.all
    @selected_criterium = Criterium.find(session[:params]["criterium"])
    @parameter_categories = ParameterCategory.all
    @analytics = Analytic.by_river_name_and_period(session[:params]["river_name"], session[:params]["period_date"])
    
    filename = "hasil analisa #{session[:params]['river_name']}-#{session[:params]['period_date'].to_date.strftime('%d-%m-%Y')}"
    
    if @analytics.any?
      save_download_information(params, filename)  
    end

    render_as_pdf('results/analytics.pdf.erb', filename)
  end

  def save_analytic_chart_as_pdf
    start_date = DateTime.new(session[:chart]["start"].to_f, 1, 1)
    end_date = DateTime.new(session[:chart]["end"].to_f, 12, 31) 
    parameter = Parameter.find(session[:chart]["parameter"])
    gon.label_chart = "Grafik #{parameter.name} #{session[:chart]['river']} Tahun #{start_date.strftime("%Y")}"
    gon.label_chart = gon.label_chart + "-#{end_date.strftime("%Y")}" if session[:chart]["end"] != session[:chart]["start"]
    gon.locations = Location.by_river_name(session[:chart]["river"]).sort_by{|l| l.id}.map { |l| l.spot_name }
    gon.data = AnalyticParameter.chart_data(session[:chart]["river"], start_date, end_date, session[:chart]["parameter"])
    criterium_data = CriteriumParameter.chart_data(session[:chart]["parameter"], session[:chart]["criterium"], gon.locations.length)
    gon.data << criterium_data
    gon.unit = parameter.unit
    filename = "grafik analisa #{session[:chart]['parameter']}-#{session[:chart]['river']}-#{start_date.strftime('%d-%m-%Y')}-#{end_date.strftime('%d-%m-%Y')}"
    if gon.data.any?
      save_download_information(params, "analytic_chart")
    end
    render_as_pdf('results/analytic_chart.pdf.erb', filename)
  end

  private

  def save_download_information(params, result_type)
    email = params[:email]
    purpose_of_download = params[:purpose_of_download]
    if current_user.present?
      email = current_user.email
      purpose_of_download = "download_by_operator"
    end
    DownloadHistoryService.new(email, purpose_of_download, result_type).save_to_DB
  end

  def render_as_pdf(template, filename)
    respond_to do |format|
      format.pdf do
        render pdf: "#{filename}",
               template: template,
               javascript_delay: 5000,
               layout: 'layouts/pdf.html.erb',
               show_as_html: params.key?('debug')
      end
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
	def analytic_value_class(value, params_id)
		begin
			parameter = Parameter.find(params_id)
			selected_criterium_parameter = @selected_criterium.criterium_parameters.find_by(parameter_id: params_id)
			if parameter.criterium_type == "rentang nilai"
				value.to_f >= selected_criterium_parameter.value.to_f && value.to_f <= selected_criterium_parameter.value2.to_f ? 'black' : 'red'	
			else
				value.to_f > selected_criterium_parameter.value.to_f ? 'red' : 'black'	
			end
		rescue 
			'black'
		end
	end
end

app/views/results/_download_confirmation.html.erb
<div class="modal fade" id="download-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Konfirmasi Unduh</h4>
      </div>
      <%= form_tag(form_action, method: 'get', class: 'form-horizontal', id: 'filter', target: :_blank) do %>
        <div class="modal-body">
          <div class="form-group">
            <%= label_tag :email, "Email", class: "col-sm-3 control-label" %>
            <div class="col-sm-8">
              <%= email_field_tag :email, nil, placeholder: 'Email', class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= label_tag :purpose_of_download, "Tujuan Unduh", class: "col-sm-3 control-label" %>
            <div class="col-sm-8">
              <%= text_field_tag :purpose_of_download, nil, placeholder: 'Tujuan download', class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><i class='fa fa-reply'></i> Batal</button>
          <%= button_tag(type: "submit", id:'submit-btn', class: "btn btn-success disabled", disabled: true) do %>
            <i class="fa fa-download"></i> Unduh(PDF)
          <% end %>
        </div>
      <% end %>
    </div>
  </div>  
</div>

app/views/results/_result_map.html.erb
<% if (@locations.any?) %>
  <% my_url = "https://maps.google.com/maps/api/staticmap?size=1200x1000&sensor=false&key=AIzaSyCzN_a36W-F0Upzt7h2uRT8stdLEzC-VIE" %>
  <% @locations.each_with_index do |location, index| %> 
    <% my_url += "&markers=label:#{index+1}%7C#{location.latitude},#{location.longitude}" %>    
  <% end %>
  <!-- <p><%#= my_url %><p/> -->
  <div class="card-block">
    <div id="map-static"><%= image_tag my_url %></div>
  </div>
  <div class="legend well">
    <h4>Keterangan: </h4>
    <ul>
      <% @locations.each_with_index do |location, index| %> 
        <li><%= "#{index+1}: #{location.code}, #{location.address}" %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <%= render :partial => 'shared/no-data'%>
<% end %>

app/views/results/_result_table.html.erb
<% if @analytics.any? %>
  <table id="result-table" class="display table table-striped table-bordered " cellspacing="0" width="100%">
    <thead>
      <tr>
        <th rowspan="3">No</th>
        <th rowspan="3">Parameter</th>
        <th rowspan="3">Satuan</th>
        <th colspan=<%= @analytics.length %>>Pengambilan Contoh</th>
        <th colspan=<%= @criteria.length%>>Kriteria Mutu Air Berdasarkan Kelas</th>
      </tr>
      <tr>
        <% @analytics.each do |analytic| %>
          <th><%= analytic.location.spot_name%></th>
        <% end %>
        <th colspan=<%= @criteria.length%>>Kadar maks.(PP No. 82/2001)</th>
      </tr>
      <tr>
        <% @analytics.each do |analytic| %>
          <th><%= analytic.location.code%></th>
        <% end %>
        <% @criteria.each do |criterium| %>
          <th><%= criterium.name%></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @parameter_categories.each_with_index do |category, index| %>
        <tr>
          <td></td>
          <td class="bold"><%= "#{index + 1}. #{category.name.titleize}" %></td>
          <td></td>
          <% @analytics.each do |analytic| %>
            <td></td>
          <% end %>
          <% @criteria.each do |criterium| %>
            <td></td>
          <% end %>
        </tr>
        <% category.parameters.each_with_index do |param, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= param.name%></td>
            <td><%= param.unit%></td>
            <% @analytics.each do |analytic| %>
              <% selected_analytic_params = analytic.analytic_parameters.where(parameter_id: param.id) %>
              <% if selected_analytic_params.any? %>
                <% selected_analytic_params.each do |analytic_param| %>
                  <td class=<%= analytic_value_class(analytic_param.value, param.id) %>>
                    <% if analytic_param.special_character.present? && analytic_param.special_character != "=" %>
                      <%= analytic_param.special_character %>
                    <%end%>
                    <%= analytic_param.value %>
                  </td>
                <% end %>
              <% else %>
                <td class=<%= analytic_value_class(0, param.id) %>>0</td>
              <% end %>
            <% end %>
            <% @criteria.each do |criterium| %>
              <% selected_criterium_params = criterium.criterium_parameters.where(parameter_id: param.id) %>
              <% if selected_criterium_params.any? %>
                <% selected_criterium_params.each do |criterium_param| %>
                  <% if criterium_param.value2.present? %>
                    <td><%= criterium_param.value + "-" + criterium_param.value2 %></td>
                  <% else %>
                    <td><%= criterium_param.value %></td>
                  <% end %>
                <% end %>
              <% else %>
                <td>0</td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <!-- <table class="table table-striped table-bordered">
    <tr>
      <td>Data tidak ditemukan</td>
    </tr>
  </table> -->
  <%= render :partial => 'shared/no-data'%>    
<% end %>

app/views/results/analytic_chart.pdf.erb
<div style="width:800px;height:800px">
  <canvas id="pdfChart" width="800" height="400"></canvas>
</div>
<% if Rails.env.development? %>
  <%= wicked_pdf_javascript_include_tag "chart.js/dist/Chart.bundle" %>
<% elsif Rails.env.production? %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.js" %>
<%end%>
<script type="text/javascript">
  $(function(){
    $('#content').append('<div><h1>Hello pdf chart</h1></div>');
    var data = gon.data;

    var chartTitle = gon.label_chart;
    var chartXLabel = gon.locations;
    var unit = gon.unit;
    var datasets = [];
    for (var i = 0; i < data.length; i++) {
      var choosedColor = dynamicColors();
      var dataset = {
          label: data[i].period,
          fill: false,
          lineTension: 0.1,
          backgroundColor: choosedColor,
          borderColor: choosedColor,
          borderCapStyle: 'round',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointStyle:'circle',
          pointHoverRadius: 5,
          pointRadius: 3,
          pointHitRadius: 5,
          data: data[i].values,
          spanGaps: false,
        };
        datasets.push(dataset);
    };
    // Init chart.js
    var ctx = document.getElementById("pdfChart");
    ctx.style.display="";
    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: chartXLabel,
        datasets: datasets
      },
      options: {
        responsive: true,
        title:{
          display:true,
          text:chartTitle,
          fullWidth:true,
          fontSize:20
        },
        tooltips: {
          mode: 'index',
          intersect: false,
        },
        legend: {
          position: 'right',
        },
        hover: {
          mode: 'nearest',
          intersect: true
        },
        scales: {
          xAxes: [{
            display: true,
            scaleLabel: {
              display: true,
              labelString: 'Lokasi'
            }
          }],
          yAxes: [{
            display: true,
            scaleLabel: {
              display: true,
              labelString: unit
            },
            ticks:{
              min: 0
            }
          }]
        }
      }
    });
  });

  var dynamicColors = function() {
    var r = Math.floor(Math.random() * 255);
    var g = Math.floor(Math.random() * 255);
    var b = Math.floor(Math.random() * 255);
    return "rgb(" + r + "," + g + "," + b + ")";
  }
</script>

app/views/results/analytic_charts.html.erb
<%= render :partial => 'shared/error_without_params' %>

<div class="header-content">
  <h2 class="page-header">Grafik Analisa</h2>
</div>
<div class="row">
  <div class="col-md-12">
    <form class='form-inline' id='filter'>
      <fieldset>
        <div class="form-group">
          <%= select_tag 'river_name', options_for_select(@rivers), prompt: "Pilih sungai", class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= select_tag 'parameter', grouped_options_for_select(@parameters), prompt: "Pilih Parameter", class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= text_field_tag 'start_period', nil, placeholder: 'Mulai dari', class: 'form-control datepicker'%>
          <%= hidden_field_tag 'start_period_date'%>
        </div>
        <div class="form-group">
          <%= text_field_tag 'end_period', nil, placeholder: 'Sampai dengan', class: 'form-control datepicker'%>
          <%= hidden_field_tag 'end_period_date'%>
        </div>
        <div class="form-group">
          <%= select_tag 'criterium', options_for_select(@criteria.collect{ |c| [c.name, c.id] }), prompt: "Pilih kriteria", class: 'form-control'%>
        </div>
      </fieldset>
    </form>
  </div>
</div>
<br />  
<div class="row">
  <div class="col-md-2">
    <% if current_user.present? %>
      <%= link_to '<i class="fa fa-download"></i> Unduh(PDF)'.html_safe, results_save_analytic_chart_as_pdf_path(:format => :pdf), :class => "btn btn-success disabled", id: "download-chart-pdf", target: :_blank, disabled: true%>
    <% else %>
      <button type="button" class="btn btn-success disabled" id="download-chart-pdf" disabled><i class="fa fa-download"></i> Unduh(PDF)</button>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-12" id="result-container">
    <table id="table-empty" class="table table-striped table-bordered no-data">
      <tr>
        <td>Data tidak ditemukan</td>
      </tr>
    </table>
    <canvas style="display:none;" id="myChart" width="400" height="200"></canvas>
  </div>
</div>

<script type="text/javascript">
  $('button#download-chart-pdf').on('click', function(){
    $("#download-confirmation-modal").remove();

    $('body').append('<%= escape_javascript (render :partial => "download_confirmation", :locals => {:form_action => results_save_analytic_chart_as_pdf_path(:format => :pdf)}) %>');

    $('#download-confirmation-modal').modal('show');
  })
</script>
<%= javascript_include_tag 'analytic_charts' %>
<%= javascript_include_tag 'download_confirmation' %>

app/views/results/analytics.html.erb
<%= render :partial => 'shared/error_without_params' %>

<div class="header-content">
  <h2 class="page-header">Data Hasil Analisa</h2>
</div>
<div class="col-md-12">
  <div class="col-md-10">
    <%= form_tag(results_get_analytics_path(format: :js), method: 'get', remote: true, class: 'form-inline', id: 'filter') do %>
      <fieldset>
        <div class="form-group">
          <%= select_tag 'river_name', options_for_select(@rivers), prompt: "Pilih sungai", class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= text_field_tag 'period', nil, placeholder: 'Periode', class: 'form-control datepicker'%>
          <%= hidden_field_tag 'period_date'%>
        </div>
        <div class="form-group">
          <%= select_tag 'criterium', options_for_select(@criteria.collect{ |c| [c.name, c.id] }), prompt: "Pilih kriteria", class: 'form-control'%>
        </div>
      </fieldset>
    <% end %>
  </div>
  <div class="col-md-2">
    <% if current_user.present? %>
      <%= link_to '<i class="fa fa-download"></i> Unduh(PDF)'.html_safe, results_save_analytic_as_pdf_path(:format => :pdf), :class => "btn btn-success disabled", id: "download-pdf", target: :_blank, disabled: true%>
    <% else %>
      <button type="button" class="btn btn-success disabled" id="download-pdf" disabled><i class="fa fa-download"></i> Unduh(PDF)</button>
    <% end %>
  </div>
</div>
<div class="col-md-12" id="result-container">
  <table class="table table-striped table-bordered no-data">
    <tr>
      <td>Data tidak ditemukan</td>
    </tr>
  </table>
</div>

<script type="text/javascript">
  var isAllFieldFilled = function(){
    var river = $("#river_name").val();
    var period = $("#period").val();
    var criterium = $("#criterium").val();
    if (river !== "" && period !== "" && criterium !== "") {
      return true;
    };
    return false;
  }

  $('button#download-pdf').on('click', function(){
    $("#download-confirmation-modal").remove();

    $('body').append('<%= escape_javascript (render :partial => "download_confirmation", :locals => {:form_action => results_save_analytic_as_pdf_path(:format => :pdf)}) %>');

    $('#download-confirmation-modal').modal('show');
  })

  $("#river_name").on('change', function(){
    if (isAllFieldFilled()) {
      $('#filter').trigger('submit');
    };
  })

  $("#period").on('change', function(){
    if (isAllFieldFilled()) {
      $('#filter').trigger('submit');
    };
  })

  $("#criterium").on('change', function(){
    if (isAllFieldFilled()) {
      $('#filter').trigger('submit');
    };
  })

  var dateElement = $('.datepicker').datepicker({
    format: "MM yyyy",
    startView: 1,
    minViewMode: 1,
    maxViewMode: 2
  });

  // set timestamp hiden element and hide datepicker when user change months
  dateElement.on("changeMonth", function(e){
    var elementId = e.target.id;
    $('#'+elementId+'_date').val(e.date);
    $(e.target).datepicker("hide");
  });
</script>
<%= javascript_include_tag 'download_confirmation' %>

app/views/results/analytics.pdf.erb
<h3 class="header"><%= "Hasil Analisis #{session[:params]["river_name"]} periode #{DateTime.parse(session[:params]["period_date"]).strftime("%B %Y ")}" %></h3>
<div class="col-md-12" id="result-container">
  <%= render :partial => 'result_table.html.erb' %>
</div>

app/views/results/get_all_location.js.erb
<% if @locations.any? %>
  $('#download-map-pdf').removeClass('disabled');
  $('#download-map-pdf').prop("disabled", false);
  $('a#download-map-pdf').removeAttr("disabled");
<% else %>
  $('#download-map-pdf').addClass('disabled');
  $('#download-map-pdf').prop("disabled", true);
  $('a#download-map-pdf').attr("disabled", true);
  $('a#download-map-pdf').click(function(event){
    event.preventDefault();
  });
<% end %>
$('#result-container').html('<%= escape_javascript (render "result_map") %>');

app/views/results/get_analytics.js.erb
<% if @analytics.any? %>
  $("#download-pdf").removeClass("disabled");
  $('#download-pdf').prop('disabled', false);
  $('a#download-pdf').removeAttr("disabled");
<% else %>
  $("#download-pdf").addClass("disabled");
  $('#download-pdf').prop('disabled', true);
  $('a#download-pdf').attr("disabled", true);
  $('a#download-pdf').click(function(event){
    event.preventDefault();
  });
<% end %>
$('#result-container').html('<%= escape_javascript (render "result_table") %>');

app/views/results/location.html.erb
<%= render :partial => 'shared/error_without_params' %>

<div class="header-content">
  <h2 class="page-header">Peta Lokasi Pengujian</h2>
</div>
<div class="col-md-12">
  <div class="col-md-10">
    <%= form_tag(results_get_all_location_path(format: :js), method: 'get', remote: true, class: 'form-inline', id: 'filter') do %>
      <fieldset>
        <div class="form-group">
          <%= select_tag 'river_name', options_for_select(@rivers), prompt: "Pilih sungai", class: 'form-control'%>
        </div>
      </fieldset>
    <% end %>
  </div>
  <div class="col-md-2">
    <% if current_user.present? %>
      <%= link_to '<i class="fa fa-download"></i> Unduh(PDF)'.html_safe, results_save_map_image_as_pdf_path(:format => :pdf), :class => "btn btn-success disabled", id: "download-map-pdf", target: :_blank, disabled: true%>
    <% else %>
      <button type="button" class="btn btn-success disabled" id="download-map-pdf" disabled><i class="fa fa-download"></i> Unduh(PDF)</button>
    <% end %>
  </div>
</div>
<div class="col-md-12" id="result-container">
  <table id="empty-result" class="table table-striped table-bordered no-data">
    <tr>
      <td>Data tidak ditemukan</td>
    </tr>
  </table>
</div>

<script type="text/javascript">
  $("#river_name").on('change', function(){
    $('#filter').trigger('submit');
  });

  $('button#download-map-pdf').on('click', function(){
    $("#download-confirmation-modal").remove();

    $('body').append('<%= escape_javascript (render :partial => "download_confirmation", :locals => {:form_action => results_save_map_image_as_pdf_path(:format => :pdf)}) %>');

    $('#download-confirmation-modal').modal('show');
  })
</script>

<%= javascript_include_tag 'download_confirmation' %>

app/views/results/maps.pdf.erb
<h3 class="header"><%= "Peta Lokasi #{session[:location_params]["river_name"]}" %></h3>
<div class="col-md-12" id="result-container">
  <%= render :partial => 'result_map.html.erb' %>
</div>